sudo: true
language: cpp
os:
- osx
compiler:
- gcc
cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
script:
- curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/macpython-download-cache-and-build-module-wheels.sh -O
- chmod u+x macpython-download-cache-and-build-module-wheels.sh
- ./macpython-download-cache-and-build-module-wheels.sh
- tar -zcvf dist.tar.gz dist/
- curl --upload-file dist.tar.gz https://transfer.sh/dist.tar.gz
