branches:
 only:
  - master

version: "0.0.1.{build}"

install:

  - curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/windows-download-cache-and-build-module-wheels.ps1 -O
  - ps: $env:ITK_PACKAGE_VERSION='v4.13.0'; .\windows-download-cache-and-build-module-wheels.ps1

build: off

test: off

artifacts:

  # pushing entire folder as a zip archive
  - path: dist\*

deploy: off
