version: 2
jobs:
  build-and-test:
    working_directory: ~/ITKUltrasound-build
    docker:
      - image: insighttoolkit/module-ci:latest
    steps:
      - checkout:
          path: ~/ITKUltrasound
      - run:
          name: Configure
          command: |
            SHASNIP=$(echo $CIRCLE_SHA1 | cut -c1-7)
            cmake \
              -DITK_DIR:PATH=/ITK-build \
              -DBUILD_TESTING:BOOL=ON \
              -DBUILDNAME:STRING=External-ITKUltrasound-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}-${SHASNIP} \
                ~/ITKUltrasound
      - run:
          name: Build and Test
          no_output_timeout: 1.0h
          environment:
            CTEST_BUILD_FLAGS: "-j5"
          command: |
            ctest -j 2 -VV -D Experimental
  package:
    working_directory: ~/ITKUltrasound
    machine: true
    steps:
      - checkout
      - run:
          name: Fetch build script
          command: |
            curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
            chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            ./dockcross-manylinux-download-cache-and-build-module-wheels.sh
      - store_artifacts:
          path: dist
          destination: dist

workflows:
    version: 2
    build-test-package:
      jobs:
        - build-and-test
        - package
